[Ci] clean up the old artifacts in the agent before downloading the new artifacts
sonic-net/sonic-buildimage pull request #12391
Opened 2022-10-13 15:24 UTC by xumia

…ew artifacts

#### Why I did it
The vs build failed but some of the test passed.
See build: https://dev.azure.com/mssonic/build/_build/results?buildId=159753&view=logs&jobId=e2a1d004-6151-514d-dd3b-ba225f574bd9&j=e2a1d004-6151-514d-dd3b-ba225f574bd9&t=f0777b63-8377-5b65-c700-6568122e76b9

```
[ FAIL LOG START ] [ target/python-wheels/buster/sonic_yang_models-1.0-py3-none-any.whl ]
[ REASON ] :      target/python-wheels/buster/sonic_yang_models-1.0-py3-none-any.whl does not exist   NON-EXISTENT PREREQUISITES: target/debs/buster/libyang_1.0.73_amd64.deb-install target/debs/buster/libyang-cpp_1.0.73_amd64.deb-install target/debs/buster/python3-yang_1.0.73_amd64.deb-install 
[ FLAGS  FILE    ] : [] 
[ FLAGS  DEPENDS ] : [vs amd64 buster] 
[ FLAGS  DIFF    ] : [vs amd64 buster ] 
/sonic/src/sonic-yang-models /sonic
running pytest
Searching for ijson==2.6.1
Reading https://pypi.org/simple/ijson/

```

![image](https://user-images.githubusercontent.com/59720581/195638595-d5b28d4b-a74e-487d-8402-a558daaff871.png)

#### How I did it
Clean up the old artifacts.

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

#### Description for the changelog

#### Ensure to add label/tag for the feature raised. example - PR#2174 under sonic-utilities repo. where, Generic Config and Update feature has been labelled as GCU.

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2022-10-20 09:13 UTC, liushilongbuaa commented on azure-pipelines.yml
> +        sudo rm -rf ../target
It's better to set '-e'

2022-10-20 09:14 UTC, liushilongbuaa requested changes

2022-10-20 09:14 UTC, liushilongbuaa commented on azure-pipelines.yml
> +        sudo rm -rf ../target
set -e
sudo rm -rf ../target

2022-10-25 07:42 UTC, xumia commented on .azure-pipelines/run-test-template.yml
> +    sudo rm -rf ../target
sudo rm ../target

2022-10-25 07:43 UTC, xumia commented on .azure-pipelines/run-test-template.yml
> +  displayName: "Cleanup"
```suggestion
    sudo rm -rf ../target
  displayName: "Cleanup"
```

2022-10-25 07:45 UTC, merged