[build] use pip install of later setup.py to install test dependencies
sonic-net/sonic-buildimage pull request #13374
Opened 2023-01-16 07:52 UTC by liushilongbuaa

#### Why I did it

#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

#### Description for the changelog

#### Ensure to add label/tag for the feature raised. example - PR#2174 under sonic-utilities repo. where, Generic Config and Update feature has been labelled as GCU.

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-01-17 07:13 UTC, liushilongbuaa commented
/azpw run Azure.sonic-buildimage

2023-01-17 07:14 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-buildimage

2023-01-17 10:13 UTC, xumia commented on slave.mk
> +		echo ==================== end test 1>&2
We need to run line 879 before testing, right?

2023-01-30 02:09 UTC, liushilongbuaa commented
/azpw run Azure.sonic-buildimage

2023-01-30 02:09 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-buildimage

2023-02-02 06:14 UTC, qiluo-msft requested changes
Offline discussed. This issue is that dev is `python3 setup.py test` in sub repo's folder directly.

2023-02-02 07:23 UTC, liushilongbuaa commented
> Offline discussed. This issue is that dev is `python3 setup.py test` in sub repo's folder directly.

We can discuss this issue next week. But this PR still can be merged as a fix for deepdiff's root cause.

2023-02-03 09:37 UTC, xumia commented on slave.mk
> +		if [ ! "$($*_TEST)" = "n" ]; then python$($*_PYTHON_VERSION) $(BUILD_WORKDIR)/scripts/get_py_depend.py | xargs -i pip$($*_PYTHON_VERSION) install {}; python$($*_PYTHON_VERSION) setup.py test; fi $(
How about moving the logic inside of the python program get_py_depend.py (give a better name).

2023-02-22 05:23 UTC, closed without merging