Change SECURE_UPGRADE_DEV_SIGNING_CERT to SECURE_UPGRADE_SIGNING_CERT
sonic-net/sonic-buildimage pull request #14591
Opened 2023-04-10 13:52 UTC by DavidZagury

Depends on https://github.com/sonic-net/sonic-linux-kernel/pull/315

#### Why I did it
The name SECURE_UPGRADE_DEV_SIGNING_CERT is misleading, this flag is relevant to both to dev and prod signing.

#### How I did it
Change all mentions of name SECURE_UPGRADE_DEV_SIGNING_CERT to SECURE_UPGRADE_SIGNING_CERT - this is also done with PR in sonic-linux-kernel repository

#### How to verify it
Build SONiC using your own prod script

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [x] 202211

#### Description for the changelog

#### Ensure to add label/tag for the feature raised. example - PR#2174 under sonic-utilities repo. where, Generic Config and Update feature has been labelled as GCU.

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-04-13 11:19 UTC, liat-grozovik commented
@davidpil2002 could you please help to review as well?

2023-04-13 14:41 UTC, davidpil2002 submitted a review, later dismissed

2023-04-13 14:47 UTC, xumia submitted a review, later dismissed

2023-04-18 23:06 UTC, qiluo-msft submitted a review, later dismissed

2023-04-21 18:21 UTC, DavidZagury commented
/azpw run Azure.sonic-buildimage

2023-04-21 18:21 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-buildimage

2023-04-24 18:17 UTC, merged

2023-04-30 10:01 UTC, TheZinna requested changes
[]()

2023-05-15 08:40 UTC, mssonicbld commented
Cherry-pick PR to 202211: https://github.com/sonic-net/sonic-buildimage/pull/15066