Add override_config to load_minigraph in config-setup service
sonic-net/sonic-buildimage pull request #14834
Opened 2023-04-25 01:06 UTC by judyjoseph

#### Why I did it

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-04-25 19:26 UTC, qiluo-msft commented on files/image_config/config-setup/config-setup
> +        config load_minigraph -y -n -t --override_config
Let's add explicit path `/etc/sonic/golden_config_db.json`

2023-04-28 18:14 UTC, judyjoseph commented on files/image_config/config-setup/config-setup
> +        config load_minigraph -y -n -t --override_config
updated

2023-04-28 21:41 UTC, qiluo-msft approved these changes

2023-05-09 06:08 UTC, qiluo-msft commented on files/image_config/config-setup/config-setup
> +    config load_minigraph -y -n --override_config --golden_config_path '/etc/sonic/golden_config_db.json'
>'/etc/sonic/golden_config_db.json' [](http://example.com/codeflow?start=71&length=34)

Please check file exists, if not, use original code.

2023-05-09 06:08 UTC, qiluo-msft requested changes
As comment

2023-05-09 23:56 UTC, qiluo-msft submitted a review, later dismissed

2023-05-10 01:42 UTC, judyjoseph commented on files/image_config/platform/rc.local
> +        GOLDEN_CONFIG_DB_FILE=$NOS_DIR/golden_config_db.json
added golden_config_db.json file handling here too.

2023-05-10 04:56 UTC, wen587 approved these changes

2023-05-10 05:58 UTC, qiluo-msft approved these changes

2023-05-10 18:54 UTC, merged

2023-06-03 00:43 UTC, gechiang commented
Removed label "Chassis for 202205 branch" since it has  been "Included in 202205 Branch" already.