Add support for x86_64-mlnx_msn2700-r0 comex respin
sonic-net/sonic-buildimage pull request #15996
Opened 2023-07-31 05:53 UTC by Junchao-Mellanox

#### Why I did it

Add new hardware respined version support for x86_64-mlnx_msn2700-r0

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

1. new pcie.yaml
2. new sensors.conf
3. new thermal support
4. new platform.json file
5. adjust test code

#### How to verify it

Run sonic-mgmt regression test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-07-31 05:55 UTC, keboliu approved these changes

2023-08-01 01:47 UTC, Junchao-Mellanox commented
/azpw run Azure.sonic-buildimage

2023-08-01 01:47 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-buildimage

2023-08-24 10:37 UTC, liat-grozovik requested changes

2023-08-24 10:37 UTC, liat-grozovik commented on device/mellanox/x86_64-mlnx_msn2700-r0/get_sensors_conf_path
> +    RESPIN_VERSION=$(python3 -c "import sonic_platform;print(sonic_platform.device_data.DeviceDataManager.get_respin_version())")
Use VERSION and A1 when needed

2023-08-25 06:14 UTC, Junchao-Mellanox commented
/azpw run Azure.sonic-buildimage

2023-08-25 06:14 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-buildimage

2023-08-27 07:16 UTC, liat-grozovik approved these changes

2023-09-10 15:23 UTC, liat-grozovik approved these changes

2023-09-21 05:32 UTC, closed without merging