[202205] Disable interrupt for intel i2c-i801 driver
sonic-net/sonic-buildimage pull request #16277
Opened 2023-08-24 22:06 UTC by prgeor

#### Why I did it

On S6100 we are seeing almost 100K interrupts per second on intels i801 SMBUS controller which affects systems performance. This interrupt storm has already been fixed in newer kernel with a fix here:-

In 202205 branch (using old kernel (5.10)) disable the interrupt and enable the polling for i2c-i801 driver

<img width="834" alt="image" src="https://github.com/sonic-net/sonic-buildimage/assets/45705344/c33296e7-4d34-45a9-a830-4d78c5450794">

##### Work item tracking
- Microsoft ADO **(number only)**:24910530

#### How I did it
Disable the interrupt by passing the interrupt disable feature argument to i2c-i801 driver

#### How to verify it
1. On SN2700 its already disabled in Mellanox hw-mgmt
2. Arista 7050CX3 don't use i801 
3. Celestica DX010 
4. Dell S6100 verified the interrupts are no longer incrementing.
5. 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

Disable interrupt for intel i2c-i801 driver

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-08-25 17:19 UTC, prgeor commented
@Staphylo can you review from Arista platform pov?

2023-08-26 00:09 UTC, yxieca commented
@prgeor should there be a master branch PR for this change and we cherry-pick it?

2023-08-27 04:46 UTC, prgeor commented
> @prgeor should there be a master branch PR for this change and we cherry-pick it?

@yxieca master already has latest kernel where this interrupt is by default disabled

2023-08-28 11:24 UTC, Staphylo requested changes
Hi @prgeor, your change should be fine for our platforms.
However I noticed a syntax error that will break `logs_inram`

On a more general note with this change:
I haven't seen any high interrupt issue on this product. Also I'm not sure where the statement that disabling the IRQ became the default. Looking at the kernel sources the FEATURE_IRQ is enabled on the latest 5.10 and mainline kernel.
The performance is slightly degraded after disabling this feature.
However there should not be any impact to our software since we don't use this smbus controller for much.

2023-08-28 16:35 UTC, prgeor commented on files/Aboot/boot0.j2
> +        cmdline_add logs_inram=on, i2c-i801.disable_features=0x10
@Staphylo added in new line

2023-08-28 17:41 UTC, prgeor commented
@yxieca Just realized, this fix needs to be in master

> > @prgeor should there be a master branch PR for this change and we cherry-pick it?
> 
> @yxieca master already has latest kernel where this interrupt is by default disabled

@yxieca on a second look, looks like we need PR in master. So closing this

2023-08-28 17:41 UTC, closed without merging