Add support for ipv4 dhcp_server in minigraph parser
sonic-net/sonic-buildimage pull request #16313
Opened 2023-08-29 04:31 UTC by yaqiangz

#### Why I did it
Add minigraph parser support for dhcp_server in BmcMgmtToRRouter device followed https://github.com/sonic-net/SONiC/pull/1282. Parse dhcp_server related info from minigraph.

##### Work item tracking
- Microsoft ADO **(number only)**: 17695979

#### How I did it
Add minigraph parser support for dhcp_server in BmcMgmtToRRouter device.

#### How to verify it
Build image, ut passed.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-09-01 03:58 UTC, Blueve approved these changes

2023-09-05 05:25 UTC, yaqiangz commented
@yxieca Could you pls help to merge this PR?

2023-09-05 17:18 UTC, lguohan commented
@qiluo-msft , i thought we are gong to block all minigraph changes now?

2023-09-05 18:16 UTC, qiluo-msft commented on src/sonic-config-engine/minigraph.py
> +            results['DHCP_SERVER_IPV4_PORT'] = dhcp_server_ipv4_port
This is a new table in ConfigDB. Please onboard it with golden config generation pipeline. We are blocking new tables coming into minigraph parser.

2023-09-05 18:16 UTC, qiluo-msft requested changes
as comment

2023-09-12 23:17 UTC, qiluo-msft commented on src/sonic-config-engine/minigraph.py
> +            generate_ipv4_dhcp_server_config(devices, link_ports, port_alias_map, vlan_intfs, vlan_members,
>generate_ipv4_dhcp_server_config [](http://example.com/codeflow?start=12&length=32)

Why generate_ipv4_dhcp_server_config() is needed. It just manipulated existing ConfigDB, does not parse minigraph at all, no extra info added into ConfigDB. Seems like everything you needed is already in ConfigDB or as default values.

2023-09-14 08:23 UTC, closed without merging