[201911][multi-asic] Monit changes to enable internal link monitoring…
sonic-net/sonic-buildimage pull request #16393
Opened 2023-09-02 04:56 UTC by tjchadaga

… script

#### Why I did it
This PR is dependent on https://github.com/sonic-net/sonic-utilities/pull/2966. 

Monit changes to enable script to monitor SAI_PORT_STAT_IF_IN_ERRORS & SAI_PORT_STAT_IF_OUT_ERRORS on internal (backend) ports of multi-asic device.

##### Work item tracking
- Microsoft ADO **(number only)**: 15439060

#### How I did it
Added link monitoring program to monit to periodically trigger check and mitigation

#### How to verify it
On device with non-zero errors on internal links,  syslog is generated for every port and up to min_links ports with errors (within the port-channel) are automatically shutdown

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-09-07 02:14 UTC, arlakshm approved these changes

2023-09-07 03:33 UTC, abdosi approved these changes

2023-09-09 15:13 UTC, abdosi requested changes
first we need to merge this: https://github.com/sonic-net/sonic-buildimage/pull/16487

2023-09-12 22:56 UTC, abdosi approved these changes

2023-09-12 22:57 UTC, merged