Add special rsyslog filter for MSN2700 platform
sonic-net/sonic-buildimage pull request #16684
Opened 2023-09-25 09:12 UTC by keboliu

#### Why I did it

##### Work item tracking
- Microsoft ADO **(number only)**:

Mellanox MSN2700 platforms have a non-functional error log:  "ERR pmon#sensord: Error getting sensor data: dps460/#10: Can't read".  This error is because of a firmware issue with some PSU, we are not able to upgrade the FW online. Since there is no functional impact, this error log can be ignored safely.

#### How I did it

Add a new rsyslog rule to the rsyslog-container.conf.j2, if the docker name is pmon and the platform name matches, the new rule will be inserted into the docker rsyslogd.conf

#### How to verify it

run regression on the MSN2700 platform to make the error log will not be printed to the syslog.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [x] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-09-25 19:19 UTC, prgeor commented
@keboliu can we use sensord configuration file to ignore the sensor reading?

2023-09-27 05:48 UTC, keboliu commented
> @keboliu can we use sensord configuration file to ignore the sensor reading?

Hi @prgeor , sensor conf is not able to address all the scenario, it still can happen when sensord scan all the sensors in the background.

2023-09-27 06:06 UTC, Junchao-Mellanox approved these changes

2023-10-09 05:44 UTC, liat-grozovik submitted a review, later dismissed

2023-10-13 13:39 UTC, prgeor requested changes
@keboliu to prevent overwhelming the host rsyslogd, please do the filtering inside the PMON. To make this working in PMON, we need to keep this action at the end of the rsyslog conf file:-https://github.com/sonic-net/sonic-buildimage/blob/master/files/image_config/rsyslog/rsyslog-container.conf.j2#L56

2023-10-20 10:29 UTC, keboliu commented
> @keboliu to prevent overwhelming the host rsyslogd, please do the filtering inside the PMON. To make this working in PMON, we need to keep this action at the end of the rsyslog conf file:-https://github.com/sonic-net/sonic-buildimage/blob/master/files/image_config/rsyslog/rsyslog-container.conf.j2#L56

I tried to add the rule to the rsyslog.conf inside pmon docker, but it doesn't work.

2023-10-23 06:36 UTC, prgeor commented
@saiarcot895 could you review?

2023-10-23 20:36 UTC, saiarcot895 approved these changes

2023-10-24 14:51 UTC, prgeor commented
@liat-grozovik @lguohan please merge

2023-10-24 14:53 UTC, liat-grozovik approved these changes

2023-10-24 14:54 UTC, merged

2023-10-25 05:44 UTC, keboliu commented
@yxieca @StormLiangMS  would you please help to cherry-pick?

2023-10-25 23:43 UTC, mssonicbld commented
@keboliu PR conflicts with 202205 branch

2023-10-25 23:43 UTC, mssonicbld commented
Cherry-pick PR to 202211: https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-10-25 23:45 UTC, yxieca commented
@keboliu please enter PR for 202205 branch for this change. Thanks!

2023-10-26 03:08 UTC, keboliu commented
> @keboliu please enter PR for 202205 branch for this change. Thanks!

Hi @yxieca  thanks, https://github.com/sonic-net/sonic-buildimage/pull/17020 has been created for 202205

2023-10-26 03:16 UTC, yxieca commented
> > @keboliu please enter PR for 202205 branch for this change. Thanks!
> 
> Hi @yxieca thanks, #17020 has been created for 202205

Thanks! Much appreciated!

2023-10-29 01:34 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-10-29 22:33 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-10-30 01:32 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-10-30 22:33 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-10-31 01:31 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-10-31 22:33 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-11-01 01:36 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-11-01 06:39 UTC, keboliu commented
> @keboliu cherry pick PR didn't pass PR checker. Please check!!!#17013

Hi, @StormLiangMS. It seems that some openssh version related fix is not included in the 202211 branch and are causing a build fail, would you please help to check?

2023-11-01 22:33 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-11-02 14:47 UTC, StormLiangMS commented
Hi @keboliu pls have the tested branch info updated in the description part if need cherry pick to old branches.

2023-11-02 14:48 UTC, mssonicbld commented
Cherry-pick PR to 202305: https://github.com/sonic-net/sonic-buildimage/pull/17078

2023-11-02 22:33 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-11-03 01:31 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-11-03 22:33 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-11-04 01:30 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013

2023-11-04 22:33 UTC, mssonicbld commented
@keboliu cherry pick PR didn't pass PR checker. Please check!!!<br>https://github.com/sonic-net/sonic-buildimage/pull/17013