Check if PSU files exists when getting psu_voltage properties
sonic-net/sonic-buildimage pull request #17042
Opened 2023-10-30 19:45 UTC by oleksandra-bella

### Why I did it 
Error messages occured when trying to read PSU files on init: 
`ERR pmon#psud: Failed to read from file /var/run/hw-management/power/psu1_volt_out2_capability - FileNotFoundError(2, 'No such file or directory')`

This can happen when the power cord is disconnected from the PSU, so some PSU files may be absent, e.g.: 
/var/run/hw-management/power/psu2_volt_out2
/var/run/hw-management/power/psu2_volt_out2_capability

### How I did it 
Check if a file exists for a specific PSU parameter If not, return None so we can't read the PSU file any further

### How to verify it
1. Disconnect power cord from PSU and power supply from system
2. Wait few minutes and then connect power supply to system without power cord
3. Check logs for errors

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-12-12 19:33 UTC, prgeor submitted a review, later dismissed

2023-12-18 03:12 UTC, stephenxs requested changes
IMO it should be the caller's responsibility to guarantee the PSU is available before calling such APIs.
So, I suggest fixing it by checking the PSU availability before calling the APIs.

2024-02-28 00:42 UTC, prgeor commented
> IMO it should be the caller's responsibility to guarantee the PSU is available before calling such APIs. So, I suggest fixing it by checking the PSU availability before calling the APIs.

@oleksandra-bella please address comment

2024-02-28 02:07 UTC, oleksandra-bella commented
> > IMO it should be the caller's responsibility to guarantee the PSU is available before calling such APIs. So, I suggest fixing it by checking the PSU availability before calling the APIs.
> 
> @oleksandra-bella please address comment

I've already fixed the comment by checking PSU file availability before calling the APIs

2024-02-28 02:36 UTC, stephenxs approved these changes

2024-03-04 16:19 UTC, prgeor approved these changes

2024-03-04 16:19 UTC, prgeor commented
@liat-grozovik please help merge

2024-03-04 17:34 UTC, liat-grozovik approved these changes

2024-03-04 17:35 UTC, merged