[Mellanox] Disable SSD NCQ on Mellanox platforms
sonic-net/sonic-buildimage pull request #17567
Opened 2023-12-19 15:01 UTC by volodymyrsamotiy

#### Why I did it
Based on some research some products might experience an occasional IO failures in the communication between CPU and SSD because of NCQ.
There seems to be a problem between some kernel versions and some SATA controllers.

Syslog error message examples:
- Error "ata1: SError: { UnrecovData Handshk }" - "failed command: WRITE FPDMA QUEUED".
- Error "ata1: SError: { RecovComm HostInt PHYRdyChg CommWake 10B8B DevExch }" - "failed command: READ FPDMA QUEUED".

Some vendors already disabled NCQ on their platforms in SONiC due to similar issue:
- https://github.com/sonic-net/sonic-buildimage/pull/13739 [Arista] Disable ATA NCQ for a few products
- https://github.com/sonic-net/sonic-buildimage/pull/13964 [Arista] Disable SSD NCQ on DCS-7050CX3-32S

Also there are other discussions on Debian/Ubuntu forums about similar issues and it was suggested to disable NCQ:
- https://askubuntu.com/questions/133946/are-these-sata-errors-dangerous

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Add a kernel parameter to tell libata to disable NCQ

#### How to verify it
Use FIO tool - `fio --direct=1 --rw=randrw --bs=64k --ioengine=libaio --iodepth=64 --runtime=120 --numjobs=4`

**Test results with NCQ enabled:**
```
 READ: bw=128MiB/s (135MB/s), 128MiB/s-128MiB/s (135MB/s-135MB/s), io=247MiB (259MB), run=1924-1924msec
WRITE: bw=131MiB/s (138MB/s), 131MiB/s-131MiB/s (138MB/s-138MB/s), io=253MiB (265MB), run=1924-1924msec
…
 READ: bw=130MiB/s (136MB/s), 130MiB/s-130MiB/s (136MB/s-136MB/s), io=247MiB (259MB), run=1902-1902msec
WRITE: bw=133MiB/s (139MB/s), 133MiB/s-133MiB/s (139MB/s-139MB/s), io=253MiB (265MB), run=1902-1902msec
…
 READ: bw=129MiB/s (135MB/s), 129MiB/s-129MiB/s (135MB/s-135MB/s), io=247MiB (259MB), run=1919-1919msec
WRITE: bw=132MiB/s (138MB/s), 132MiB/s-132MiB/s (138MB/s-138MB/s), io=253MiB (265MB), run=1919-1919msec
```

**Test results with NCQ disabled:**
```
 READ: bw=105MiB/s (110MB/s), 105MiB/s-105MiB/s (110MB/s-110MB/s), io=247MiB (259MB), run=2354-2354msec
WRITE: bw=107MiB/s (113MB/s), 107MiB/s-107MiB/s (113MB/s-113MB/s), io=253MiB (265MB), run=2354-2354msec
…
 READ: bw=105MiB/s (110MB/s), 105MiB/s-105MiB/s (110MB/s-110MB/s), io=247MiB (259MB), run=2349-2349msec
WRITE: bw=108MiB/s (113MB/s), 108MiB/s-108MiB/s (113MB/s-113MB/s), io=253MiB (265MB), run=2349-2349msec
…
 READ: bw=105MiB/s (110MB/s), 105MiB/s-105MiB/s (110MB/s-110MB/s), io=247MiB (259MB), run=2349-2349msec
WRITE: bw=108MiB/s (113MB/s), 108MiB/s-108MiB/s (113MB/s-113MB/s), io=253MiB (265MB), run=2349-2349msec
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-12-19 15:05 UTC, mssonicbld commented
@StormLiangMS,@liushilongbuaa PR: https://github.com/sonic-net/sonic-buildimage/pull/17567 is conflict with MS internal repo<br>Please complete the following PR by pushing fix commit to sonicbld/conflict_prefix/17567-fix<br>https://msazure.visualstudio.com/One/_git/Networking-acs-buildimage/pullrequest/9264755<br>Then comment "/azpw ms_conflict" to rerun PR checker.

2023-12-19 16:52 UTC, bingwang-ms commented
@saiarcot895 Could you please help review? Thanks!

2023-12-19 16:52 UTC, bingwang-ms commented
How about the SN2700 A1?

2023-12-20 02:40 UTC, liushilongbuaa commented
/azpw ms_conflict

2023-12-25 09:02 UTC, liat-grozovik commented
@volodymyrsamotiy you are missing SN5600 as well as SN2700-A1.
please go over the list of systems. BTW. this means you will have conflict with 2205 thus please update the missing systems and create a backport PR for 202205

2023-12-25 09:03 UTC, liat-grozovik requested changes
@volodymyrsamotiy you are missing SN5600 as well as SN2700-A1.
please go over the list of systems. BTW. this means you will have conflict with 2205 thus please update the missing systems and create a backport PR for 202205

2024-01-03 01:10 UTC, StormLiangMS commented
@liat-grozovik are we good to go?

2024-01-04 01:40 UTC, yxieca commented
> @volodymyrsamotiy you are missing SN5600 as well as SN2700-A1. please go over the list of systems. BTW. this means you will have conflict with 2205 thus please update the missing systems and create a backport PR for 202205

@liat-grozovik can we move forward with this PR and handle 5600 and 2700-A1 with another PR?

2024-01-04 01:49 UTC, yxieca commented
/azpw ms_conflict

2024-01-04 01:57 UTC, mssonicbld commented
@StormLiangMS,@liushilongbuaa PR: https://github.com/sonic-net/sonic-buildimage/pull/17567 is conflict with MS internal repo<br>Please complete the following PR by pushing fix commit to sonicbld/conflict_prefix/17567-fix<br>https://msazure.visualstudio.com/One/_git/Networking-acs-buildimage/pullrequest/9306301<br>Then comment "/azpw ms_conflict" to rerun PR checker.

2024-01-04 02:45 UTC, liushilongbuaa commented
/azpw ms_conflict

2024-01-04 07:33 UTC, volodymyrsamotiy commented
> > @volodymyrsamotiy you are missing SN5600 as well as SN2700-A1. please go over the list of systems. BTW. this means you will have conflict with 2205 thus please update the missing systems and create a backport PR for 202205
> 
> @liat-grozovik can we move forward with this PR and handle 5600 and 2700-A1 with another PR?

@yxieca, no need to handle 5600 and 2700-A1 with another PR, this PR was already updated, it has all the changes.

2024-01-04 17:05 UTC, yxieca commented
> > > @volodymyrsamotiy you are missing SN5600 as well as SN2700-A1. please go over the list of systems. BTW. this means you will have conflict with 2205 thus please update the missing systems and create a backport PR for 202205
> > 
> > 
> > @liat-grozovik can we move forward with this PR and handle 5600 and 2700-A1 with another PR?
> 
> @yxieca, no need to handle 5600 and 2700-A1 with another PR, this PR was already updated, it has all the changes.

@volodymyrsamotiy what is keeping this PR in draft mode? @liat-grozovik  any other blocking issues?

2024-01-09 21:19 UTC, bingwang-ms commented
@liat-grozovik Can we unblock this PR now?

2024-01-09 21:20 UTC, bingwang-ms commented
Removed the label for 202205 branch as another PR has been opened to 202205 https://github.com/sonic-net/sonic-buildimage/pull/17662

2024-01-10 14:37 UTC, prgeor commented
> @volodymyrsamotiy you are missing SN5600 as well as SN2700-A1. please go over the list of systems. BTW. this means you will have conflict with 2205 thus please update the missing systems and create a backport PR for 202205

@liat-grozovik i think this has been addressed so please check again

2024-01-10 14:37 UTC, prgeor approved these changes

2024-01-22 17:15 UTC, liat-grozovik approved these changes

2024-01-28 14:26 UTC, merged

2024-01-29 16:34 UTC, mssonicbld commented
@volodymyrsamotiy PR conflicts with 202311 branch

2024-01-31 01:38 UTC, yxieca commented
@volodymyrsamotiy can you help create 202311 PR?

2024-01-31 14:26 UTC, mssonicbld commented
Cherry-pick PR to 202305: https://github.com/sonic-net/sonic-buildimage/pull/17960

2024-01-31 14:26 UTC, StormLiangMS commented
ADO: 25853968