Support ASIC/SDK health event
sonic-net/sonic-buildimage pull request #17879
Opened 2024-01-23 02:14 UTC by stephenxs

#### Why I did it

Support ASIC/SDK health event: yang model update
- Suppress ASIC/SDK health event configuration
- New event

Signed-off-by: Stephen Sun <stephens@nvidia.com>

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2024-04-16 08:46 UTC, liat-grozovik commented
@qiluo-msft  @dgsudharsan  can you please help to review the PR?

2024-04-16 09:35 UTC, Junchao-Mellanox approved these changes

2024-04-17 03:24 UTC, dgsudharsan requested changes

2024-04-18 01:58 UTC, dgsudharsan approved these changes

2024-04-18 02:17 UTC, stephenxs commented on src/sonic-yang-models/yang-models/sonic-suppress-asic-sdk-health-event.yang
> +                leaf max_events {
Fixed.

2024-04-18 03:29 UTC, stephenxs commented
Seems to be a dependency issue.
The `sonic-yang-mgmt` test depends on the latest `sonic-yang-model` in this PR. But at the time when the `sonic-yang-mgmt` test was running the latest `sonic-yang-model` python wheel had not been installed.
Trying to find a quick way to resolve the dependency issue for now but if there isn't I would like to move `sample_config_db.json` into another PR depending on this one.

2024-04-19 06:57 UTC, stephenxs commented
> Seems to be a dependency issue. The `sonic-yang-mgmt` test depends on the latest `sonic-yang-model` in this PR. But at the time when the `sonic-yang-mgmt` test was running the latest `sonic-yang-model` python wheel had not been installed. Trying to find a quick way to resolve the dependency issue for now but if there isn't I would like to move `sample_config_db.json` into another PR depending on this one.

Fixed.

2024-04-30 01:33 UTC, stephenxs commented
@qiluo-msft @prsunny Could you help to review and merge the PR? This is the yang model of ASIC/SDK health event. Thanks.

2024-05-06 16:55 UTC, bingwang-ms commented
@kperumalbfn @prabhataravind Can you please help review this change?

2024-05-07 10:51 UTC, liat-grozovik commented
@zhangyanzhao @qiluo-msft could you please help to approve it on the coming yang meeting? if not, i suggest to merge it as we need it for 202405.

2024-05-07 17:24 UTC, prsunny approved these changes

2024-05-07 17:25 UTC, prsunny commented
@kperumalbfn , please merge once you signoff. Yang change is approved by Sudharsan.

2024-05-07 17:40 UTC, kperumalbfn approved these changes

2024-05-07 17:41 UTC, merged