[nvidia] add x86_64-nvidia_sn4280_simx-r0 platform
sonic-net/sonic-buildimage pull request #18575
Opened 2024-04-05 12:08 UTC by Yakiv-Huryk

#### Why I did it
To add a new simulation platform SN4280-simx

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added/updated all relevant files for a new device

#### How to verify it
Run Nvidia simulation on SN4280 (ASIC and Platform)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2024-04-06 00:53 UTC, vivekrnv approved these changes

2024-04-11 17:46 UTC, dgsudharsan approved these changes

2024-04-14 12:02 UTC, liat-grozovik requested changes

2024-04-15 12:26 UTC, Yakiv-Huryk commented on device/mellanox/x86_64-nvidia_sn4280_simx-r0/ACS-SN4280/buffers_defaults_t0.j2
> +{#
made it a link to SN4700

2024-04-15 12:27 UTC, Yakiv-Huryk commented on device/mellanox/x86_64-nvidia_sn4280_simx-r0/ACS-SN4280/buffers_defaults_t1.j2
> +{#
made it a link to SN4700

2024-04-15 12:27 UTC, liat-grozovik approved these changes

2024-04-15 12:28 UTC, Yakiv-Huryk commented on device/mellanox/x86_64-nvidia_sn4280_simx-r0/ACS-SN4280/hwsku.json
> +{
32 for now, once the x86_64-nvidia_sn4280-r0 is defined, the SKU will be a link to x86_64-nvidia_sn4280-r0/ACS-SN4280 (as it's done for other simx platforms)

2024-04-15 12:29 UTC, Yakiv-Huryk commented on device/mellanox/x86_64-nvidia_sn4280_simx-r0/ACS-SN4280/sai_4280.xml
> +<?xml version="1.0"?>
fixed

2024-04-15 12:30 UTC, Yakiv-Huryk commented on device/mellanox/x86_64-nvidia_sn4280_simx-r0/pcie.yaml
> +##
fixed

2024-04-23 23:14 UTC, merged