[Mellanox] Add support for platform SN5400
sonic-net/sonic-buildimage pull request #18595
Opened 2024-04-08 13:08 UTC by DavidZagury

#### Why I did it
Add support for new platform x86_64-nvidia_sn5400-r0

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added all config files that are needed to support SN5400.

#### How to verify it
Run Platform tests

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2024-04-09 07:26 UTC, stephenxs commented on device/mellanox/x86_64-nvidia_sn5400-r0/ACS-SN5400/buffers_defaults_t0.j2
> +{#
We can just make this file a symbol link to `x86_64-nvidia_sn5600-r0/ACS-SN5600/buffers_defaults_t0.j2`

2024-04-09 12:10 UTC, stephenxs commented on device/mellanox/x86_64-nvidia_sn5400-r0/ACS-SN5400/pg_profile_lookup.ini
> +##
this one can be changed to symbol link

2024-04-10 06:32 UTC, stephenxs approved these changes

2024-04-14 10:58 UTC, liat-grozovik requested changes

2024-04-14 10:58 UTC, liat-grozovik commented on device/mellanox/x86_64-nvidia_sn5400-r0/sensors.conf
> +# Copyright (c) 2019 - 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
@DavidZagury this is new file. header cannot be old.

2024-04-17 08:52 UTC, liat-grozovik approved these changes

2024-04-17 08:52 UTC, merged

2024-04-18 07:17 UTC, dprital commented
@yxieca , Can you please merge to 202311 ?

2024-04-18 18:08 UTC, yxieca commented
> @yxieca , Can you please merge to 202311 ?

@dprital this change is not a bug fix. Can it wait for 202405 branch?

2024-04-19 16:07 UTC, dprital commented
> > @yxieca , Can you please merge to 202311 ?
> 
> @dprital this change is not a bug fix. Can it wait for 202405 branch?

@liat-grozovik to comment on that.

2024-05-13 16:44 UTC, mssonicbld commented
Cherry-pick PR to 202311: https://github.com/sonic-net/sonic-buildimage/pull/18952