Pvst co pr
sonic-net/sonic-buildimage pull request #20417
Opened 2024-10-04 05:46 UTC by divyachandralekha

**What I did**
Added new STP docker and rules to compile STP
Added libevent required for STP

**How to verify it**
After this PR STP docker will be available

2024-10-09 10:36 UTC, sutharsansr approved these changes

2024-10-22 07:48 UTC, divyachandralekha commented
/azpw

2024-10-22 09:12 UTC, muhammadalihussnain commented
/azpw run Azure.sonic-buildimage

2024-10-23 04:51 UTC, divyachandralekha commented
/AzurePipelines run Azure.sonic-buildimage

2024-10-23 04:54 UTC, divyachandralekha commented
/azpw run Azure.sonic-buildimage

2024-10-23 04:54 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-buildimage

2024-10-23 07:02 UTC, ridahanif96 commented
/azpw ms_conflict

2024-10-23 15:47 UTC, divyachandralekha commented
/azpw ms_conflict

2024-10-24 07:49 UTC, divyachandralekha commented
/azpw ms_conflict

2024-10-24 07:50 UTC, divyachandralekha commented
/azpw run ms_conflict

2024-10-24 07:56 UTC, divyachandralekha commented
/azpw run

2024-10-24 07:56 UTC, mssonicbld commented
/AzurePipelines run

2024-10-24 12:08 UTC, divyachandralekha commented
/AzurePipelines run

2024-10-24 12:08 UTC, divyachandralekha commented
/azpw run

2024-10-24 12:08 UTC, mssonicbld commented
/AzurePipelines run

2024-10-24 12:10 UTC, divyachandralekha commented
/AzurePipelines run

2024-10-24 12:10 UTC, divyachandralekha commented
/azpw run

2024-10-24 12:10 UTC, mssonicbld commented
/AzurePipelines run

2024-10-24 12:13 UTC, divyachandralekha commented
/azpw run

2024-10-24 12:13 UTC, mssonicbld commented
/AzurePipelines run

2024-10-28 09:20 UTC, matiAlfaro requested changes

2024-10-28 09:20 UTC, matiAlfaro commented on .gitmodules
> +	branch = pvst_co_pr
You plan to integrate your code into sonic-net/sonic-swss right?

2024-11-04 06:32 UTC, bendrapubalareddy approved these changes

2024-11-04 06:45 UTC, bendrapubalareddy commented
It's good to attach the test results and test cases list.

2024-11-04 07:16 UTC, divyachandralekha commented
sonic-stp , sonic-utilities , sonic-swss should be merged first to resolve the failures in this repo.

2024-11-04 08:22 UTC, ridahanif96 approved these changes

2024-11-29 16:02 UTC, vinaykumar-kayyur commented
@divyachandralekha @ridahanif96 Kindly update if this PR is being actively worked upon and what would be the ETA for the commit of these changes.

2024-12-11 16:07 UTC, divyachandralekha commented
/azpw run

2024-12-11 16:07 UTC, mssonicbld commented
/AzurePipelines run

2025-02-20 08:02 UTC, closed without merging