Change the default number of Kernel dumps to 3
sonic-net/sonic-buildimage pull request #20647
Opened 2024-10-30 07:26 UTC by bmridul

#### Why I did it

Currently there is no limit on the number of kernel dumps that will be captured in the system. This leads to excessive disk space usage if the system encounters many kernel crashes (e.g. as part of sonic-mgmt test suite runs). 

According to the HLD, the default number of kdumps should be 3. However the fix is missing in code.

https://github.com/sonic-net/SONiC/blob/master/doc/kdump/SONiC-kdump.md#config-kdump-num_dumps-number

This PR is providing the fix.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Set the number of kernel dumps in /etc/default/kdump-tools

#### How to verify it
UT Log:
root@sonic:/home/cisco# show reboot h
Name                 Cause                                                                   Time                             User    Comment
-------------------  ----------------------------------------------------------------------  -------------------------------  ------  ---------
2024_08_26_19_35_54  Kernel Panic                                                            Mon Aug 26 07:32:18 PM UTC 2024  N/A     N/A
2024_08_26_19_29_47  Kernel Panic                                                            Mon Aug 26 07:26:16 PM UTC 2024  N/A     N/A
2024_08_26_19_04_03  Kernel Panic                                                            Mon Aug 26 07:00:36 PM UTC 2024  N/A     N/A
2024_08_26_18_54_39  Kernel Panic                                                            Mon Aug 26 06:51:35 PM UTC 2024  N/A     N/A
2024_08_26_18_43_13  reboot                                                                  Mon Aug 26 06:36:53 PM UTC 2024  cisco   N/A
2024_08_26_18_31_25  reboot                                                                  Mon Aug 26 06:27:02 PM UTC 2024  cisco   N/A
2024_08_26_16_19_34  reboot                                                                  Mon Aug 26 04:13:14 PM UTC 2024  cisco   N/A
2024_08_18_12_03_16  reboot due to inactive RP (headless) [Time: Sun 18 Aug 2024 12:00:02 ]  N/A                              N/A     N/A
2024_08_17_12_41_29  reboot due to inactive RP (headless) [Time: Sat 17 Aug 2024 12:38:04 ]  N/A                              N/A     N/A
2024_08_17_12_16_33  reboot issued from RP                                                   N/A                              N/A     N/A
root@sonic:/home/cisco# show kdump files
          Kernel core dump files                        Kernel dmesg files
------------------------------------------  ------------------------------------------
/var/crash/202408261932/kdump.202408261932  /var/crash/202408261932/dmesg.202408261932
/var/crash/202408261926/kdump.202408261926  /var/crash/202408261926/dmesg.202408261926
/var/crash/202408261900/kdump.202408261900  /var/crash/202408261900/dmesg.202408261900
root@sonic:/home/cisco# ls /var/crash/
202408261900  202408261926  202408261932  kdump_lock  kexec_cmd

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)
202405

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2024-10-30 07:32 UTC, bmridul commented
@prgeor , Pls review

2024-10-30 23:29 UTC, bmridul commented
@abdosi , Pls check

2024-11-01 00:18 UTC, abdosi approved these changes

2024-11-01 00:19 UTC, abdosi commented
@saiarcot895 : can you please review this.

2024-11-01 00:59 UTC, saiarcot895 requested changes
This doesn't appear to be needed. On a device where kdump is disabled, running `sudo config kdump enable` modifies `/etc/default/kdump-tools` and sets `KDUMP_NUM_DUMPS` to `3`.

2024-11-04 07:45 UTC, bmridul commented
> This doesn't appear to be needed. On a device where kdump is disabled, running `sudo config kdump enable` modifies `/etc/default/kdump-tools` and sets `KDUMP_NUM_DUMPS` to `3`.

The above assumes that the kernel dump is explicitly enabled by CLI. We have enabled kdump by default in this PR for Cisco platforms.
https://github.com/sonic-net/sonic-buildimage/pull/16224
With that the KDUMP_NUM_DUMPS is not set as default in /etc/default/kdump-tools

2024-11-14 01:17 UTC, saiarcot895 commented
@bmridul That's because hostcfgd is not applying the changes from the default state to the runtime configuration. Please modify hostcfgd to add proper support for this.

2024-11-14 06:26 UTC, bmridul commented
> @bmridul That's because hostcfgd is not applying the changes from the default state to the runtime configuration. Please modify hostcfgd to add proper support for this.

Ack. I will check.

2025-01-10 07:29 UTC, bmridul commented
Closing this PR and opened https://github.com/sonic-net/sonic-host-services/pull/202

2025-01-10 07:29 UTC, closed without merging

2025-01-15 18:50 UTC, bmridul commented
@saiarcot895 , Pls review https://github.com/sonic-net/sonic-host-services/pull/202