[Mellanox] Enable get_rx_los API support in CMIS cable host mgmt mode
sonic-net/sonic-buildimage pull request #20743
Opened 2024-11-08 21:46 UTC by mihirpat1

#### Why I did it
The `show int transceiver status PORT` CLI always displays Rx LOS as False for all the lanes.

```
root@sonic:/home/admin# show int transceiver status Ethernet0 | grep "Rx loss"
        Rx loss of signal flag on media lane 1: False
        Rx loss of signal flag on media lane 2: False
        Rx loss of signal flag on media lane 3: False
        Rx loss of signal flag on media lane 4: False
        Rx loss of signal flag on media lane 5: False
        Rx loss of signal flag on media lane 6: False
        Rx loss of signal flag on media lane 7: False
        Rx loss of signal flag on media lane 8: False
root@sn5600-s1:/home/admin# 
```
##### Work item tracking
- Microsoft ADO **(number only)**: 30180403

#### How I did it
On Mellanox platforms, the `get_rx_los` API is overridden through the platform implementation (https://github.com/sonic-net/sonic-buildimage/blob/679997639ede79a7beef53654be101b14d04b006/platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py#L1069) rather than using the implementation defined through cmis.py (https://github.com/sonic-net/sonic-platform-common/blob/59babf59f9aa611b84082896391b01a39ffcb866/sonic_platform_base/sonic_xcvr/api/public/cmis.py#L404).

The Mellanox platform is overriding the `get_rx_los` due to the below code
https://github.com/sonic-net/sonic-buildimage/blob/679997639ede79a7beef53654be101b14d04b006/platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py#L1188-L1189

The current platform implementation assigns Rx LOS as False for all the lanes (irrespective of the actual status on the module) which in turn causes the `show int transceiver status PORT` CLI to display the Rx LOS as False for all the lanes.

Hence, removing the overriding part to ensure that the API is not overridden by the platform.

#### How to verify it
Verified the CLI on first 2 lanes which are in admin disabled state from the peer side.

```
root@sonic:/home/admin# show int transceiver status Ethernet0 | grep "Rx loss"
        Rx loss of signal flag on media lane 1: False
        Rx loss of signal flag on media lane 2: False
        Rx loss of signal flag on media lane 3: True
        Rx loss of signal flag on media lane 4: True
        Rx loss of signal flag on media lane 5: True
        Rx loss of signal flag on media lane 6: True
        Rx loss of signal flag on media lane 7: True
        Rx loss of signal flag on media lane 8: True
root@sn5600-s2:/home/admin# 
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2024-11-08 21:50 UTC, prgeor submitted a review, later dismissed

2024-11-08 21:50 UTC, prgeor commented
@liat-grozovik @Junchao-Mellanox can you also review

2024-11-11 03:02 UTC, Junchao-Mellanox approved these changes

2024-11-11 03:12 UTC, keboliu requested changes
There is a limitation on the Mellanox platform to support RX LOS reading in FW control mode, this change will also enable the RX LOS reading in FW control mode, we should have a logic to differentiate between FW control mode and host mgmt mode. @Junchao-Mellanox

2024-11-11 03:19 UTC, Junchao-Mellanox commented
> There is a limitation on the Mellanox platform to support RX LOS reading in FW control mode, this change will also enable the RX LOS reading in FW control mode, we should have a logic to differentiate between FW control mode and host mgmt mode. @Junchao-Mellanox

Thanks for catching this. Indeed, we need do something like following:
```
def get_rx_los(self):
        """Accessing rx los is not supproted, return all False

        Returns:
            list: [False] * channels
        """
        api = self.get_xcvr_api()
        if self.is_sw_control():
                return api.get_rx_los()
        return [False] * api.NUM_CHANNELS if api else None
```

2024-11-11 06:14 UTC, Junchao-Mellanox approved these changes

2024-11-11 06:16 UTC, mihirpat1 commented
> we should have a logic to differentiate between FW control mode and host mgmt mode. @Junchao-Mellanox

@Junchao-Mellanox @keboliu I have now addressed this. Can you please help in reviewing it?

2024-11-13 06:18 UTC, keboliu approved these changes

2024-11-13 18:14 UTC, prgeor approved these changes

2024-11-13 18:16 UTC, merged

2024-11-13 21:40 UTC, mihirpat1 commented
@bingwang-ms @yxieca Can you please help in merging this to 202405 and 202311?
MSFT ADO - 30180403

2024-11-13 21:48 UTC, mssonicbld commented
Cherry-pick PR to 202405: https://github.com/sonic-net/sonic-buildimage/pull/20790

2024-11-14 17:53 UTC, mssonicbld commented
Cherry-pick PR to 202311: https://github.com/sonic-net/sonic-buildimage/pull/20805