add srv6 yang model and unit tests
sonic-net/sonic-buildimage pull request #21175
Opened 2024-12-13 23:04 UTC by BYGX-wcr

#### Why I did it

To support the addition of CONFIG_DB|SRV6_MY_SID_TABLE.

##### Work item tracking
- Microsoft ADO **(number only)**: 30513277

#### How I did it

I define the YANG model based on [SRv6 HLD](https://github.com/sonic-net/SONiC/pull/1860). 

#### How to verify it

Run the unit tests and build image.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

Add srv6 yang model and unit tests to sonic-yang-models

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2024-12-13 23:04 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-16 23:20 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-17 00:47 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-17 20:18 UTC, BYGX-wcr commented on src/sonic-yang-models/yang-models/sonic-srv6.yang
> +                    when "../action = 'uDT46'";
added

2024-12-17 20:19 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-18 00:48 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-18 04:59 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-18 19:02 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-22 04:55 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-27 00:51 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-27 03:11 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-27 06:32 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-27 18:52 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-28 00:24 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2025-01-02 06:54 UTC, BYGX-wcr commented
@qiluo-msft , can you please help to review this change?

2025-01-02 16:51 UTC, abdosi commented on src/sonic-yang-models/yang-models/sonic-srv6.yang
> +                leaf vrf {
do we need VRF here ? VRF is already part of SRV6_MY_LOCATORS

2025-01-02 17:35 UTC, BYGX-wcr commented on src/sonic-yang-models/yang-models/sonic-srv6.yang
> +                leaf vrf {
Yes, the two VRF fields have different semantics. The first VRF field in SRV6_MY_LOCATORS define which VRF the locator belongs to (Note: right now, there is no use case for this field so it is just created for future use). The second VRF field in SRV6_MY_SIDs denotes which VRF should the uDT functions forwards to after the packet is decapsulated.

2025-01-02 18:31 UTC, venkatmahalingam commented on src/sonic-yang-models/yang-models/sonic-srv6.yang
> +
Can we have a single SRV6 container for both SRv6 lists.

2025-01-02 22:51 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2025-01-03 18:34 UTC, BYGX-wcr commented on src/sonic-yang-models/yang-models/sonic-srv6.yang
> +
There is only one SRv6 container, right?

2025-01-04 00:19 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2025-01-06 23:43 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2025-01-07 01:11 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2025-01-08 18:54 UTC, abdosi commented on src/sonic-yang-models/doc/Configuration.md
> +        "FCBB:BBBB:20::" : {
@BYGX-wcr : Please update example based of new scehama using locator as key.

2025-01-08 18:56 UTC, abdosi requested changes
LGTM. Please fix the example .

2025-01-08 18:57 UTC, abdosi commented on src/sonic-yang-models/yang-models/sonic-srv6.yang
> +
@venkatmahalingam : can we close this comment ?

2025-01-08 18:58 UTC, abdosi commented
@BYGX-wcr : Please change PR description to latest details.

2025-01-08 19:07 UTC, BYGX-wcr commented
> LGTM. Please fix the example .

fixed

2025-01-08 19:09 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2025-01-08 19:54 UTC, abdosi approved these changes

2025-01-08 21:52 UTC, ahsalam approved these changes

2025-01-11 01:42 UTC, abdosi commented
@lguohan : can you help merge this.

2025-01-13 17:07 UTC, merged

2025-01-15 02:01 UTC, abdosi commented
@BYGX-wcr : can you create direct PR for msft/202412 because of conflict